INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Patty", 25);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Kevin", 28);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Emily", 24);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Bob", 57);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);
INSERT INTO users (name, age) VALUES ("Eric", 27);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Free WiFi", "Tech", 1000000, "12/7", "12/9");

INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260000, 1, 3);
